version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=certledger_ec2_production_secret_key_2026
      - FABRIC_MODE=EMULATOR
      - PUBLIC_BASE_URL=http://localhost
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
